package com.phonenetworkapp;

import java.io.FileNotFoundException;
import com.graphframework.Graph;
import com.graphframework.KruskalAlg;
import com.graphframework.PrimAlgor;

public class PhoneNWDesignApp {
    public static void main(String[] args) throws FileNotFoundException {
        Graph PhLNetwork = Graph.readGraphFromFile("src/main/java/com/phonenetworkapp/network.txt");
        System.out.println("The phone network (minimum spanning tree) generated by Kruskal algorithm is as follows:");
        // PhLNetwork.printGraphh();
        
        // PrimAlgor prim = new PrimAlgor(); 
        // prim.MHPrimImplementation(PhLNetwork);
        // prim.displayResultingMST();
        // System.out.println();


        System.out.println("The phone network (minimum spanning tree) generated by min-heap based Prim algorithm "+ 
        "is as follows:");
        KruskalAlg kruskalAlg = new KruskalAlg(PhLNetwork);
        kruskalAlg.kruskalMST();
        kruskalAlg.displayResultingMST();
    }
}

