/*
 Names : 
 Nouf Khaled Algarabi 2006172 b8
 Wedyan Fawaz Almushaddaq 2105113 b8
 Aya Habib Khan 2010298 b10
 Joud Jamal Alkishi 2011026 b8
 */

package com.phonenetworkapp;


import java.io.FileNotFoundException;
import com.graphframework.KruskalAlg;
import com.graphframework.PrimAlgor;

public class PhoneNWDesignApp {
    public static void main(String[] args) throws FileNotFoundException {

        // create a new network by reading it from a file
        BluePrintsGraph PhLNetwork = BluePrintsGraph.readGraphFromFile("src/main/java/com/phonenetworkapp/network.txt");
        
        // print out MST using prim's
        System.out.println("The phone network (minimum spanning tree) generated by min-heap based Prim algorithm "+ 
        "is as follows:");
        PrimAlgor prim = new PrimAlgor(PhLNetwork);  
        prim.MHPrimImplementation();
        prim.displayResultingMST();
        System.out.println();

        // print out MST using kruskal's
        System.out.println("The phone network (minimum spanning tree) generated by Kruskal algorithm is as follows:");
        KruskalAlg kruskalAlg = new KruskalAlg(PhLNetwork);
        kruskalAlg.kruskalMST();
        kruskalAlg.displayResultingMST();
    }
}

